
import countingdays.Date;
import java.awt.Color;
import javax.swing.BorderFactory;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author root
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn = new javax.swing.JPanel();
        btnTxt = new javax.swing.JLabel();
        txtDisplay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tg1Hari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tg1Bulan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tg1Tahun = new javax.swing.JTextField();
        tg2Tahun = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tg2Bulan = new javax.swing.JTextField();
        tg2Hari = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(46, 48, 55));

        btn.setBackground(new java.awt.Color(46, 48, 55));
        btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(57, 192, 186)));
        btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMouseExited(evt);
            }
        });

        btnTxt.setBackground(new java.awt.Color(254, 254, 254));
        btnTxt.setForeground(new java.awt.Color(57, 192, 186));
        btnTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTxt.setText("HITUNG");

        javax.swing.GroupLayout btnLayout = new javax.swing.GroupLayout(btn);
        btn.setLayout(btnLayout);
        btnLayout.setHorizontalGroup(
            btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnLayout.setVerticalGroup(
            btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        txtDisplay.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        txtDisplay.setForeground(new java.awt.Color(57, 192, 186));
        txtDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDisplay.setText("0");

        jLabel1.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(57, 192, 186));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HITUNG HARI");

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(57, 192, 186));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KELOMPOK 2 | ANDRI, HESTI, MUAYANAH | 17CIDB");

        tg1Hari.setBackground(new java.awt.Color(46, 48, 55));
        tg1Hari.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        tg1Hari.setForeground(new java.awt.Color(57, 192, 186));
        tg1Hari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tg1Hari.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(57, 192, 186)));
        tg1Hari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tg1HariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tg1HariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tg1HariKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(57, 192, 186));
        jLabel3.setText("Tanggal");

        tg1Bulan.setBackground(new java.awt.Color(46, 48, 55));
        tg1Bulan.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        tg1Bulan.setForeground(new java.awt.Color(57, 192, 186));
        tg1Bulan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tg1Bulan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(57, 192, 186)));
        tg1Bulan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tg1BulanKeyTyped(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(57, 192, 186));
        jLabel4.setText("Bulan");

        jLabel5.setForeground(new java.awt.Color(57, 192, 186));
        jLabel5.setText("Tahun");

        tg1Tahun.setBackground(new java.awt.Color(46, 48, 55));
        tg1Tahun.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        tg1Tahun.setForeground(new java.awt.Color(57, 192, 186));
        tg1Tahun.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tg1Tahun.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(57, 192, 186)));
        tg1Tahun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tg1TahunKeyTyped(evt);
            }
        });

        tg2Tahun.setBackground(new java.awt.Color(46, 48, 55));
        tg2Tahun.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        tg2Tahun.setForeground(new java.awt.Color(57, 192, 186));
        tg2Tahun.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tg2Tahun.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(57, 192, 186)));
        tg2Tahun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tg2TahunKeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(57, 192, 186));
        jLabel6.setText("Tahun");

        jLabel7.setForeground(new java.awt.Color(57, 192, 186));
        jLabel7.setText("Bulan");

        tg2Bulan.setBackground(new java.awt.Color(46, 48, 55));
        tg2Bulan.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        tg2Bulan.setForeground(new java.awt.Color(57, 192, 186));
        tg2Bulan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tg2Bulan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(57, 192, 186)));
        tg2Bulan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tg2BulanKeyTyped(evt);
            }
        });

        tg2Hari.setBackground(new java.awt.Color(46, 48, 55));
        tg2Hari.setFont(new java.awt.Font("Ubuntu Light", 0, 14)); // NOI18N
        tg2Hari.setForeground(new java.awt.Color(57, 192, 186));
        tg2Hari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tg2Hari.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(57, 192, 186)));
        tg2Hari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tg2HariKeyTyped(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(57, 192, 186));
        jLabel8.setText("Tanggal");

        jLabel9.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(243, 91, 105));
        jLabel9.setText("Dari");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(57, 192, 186)));

        jLabel10.setFont(new java.awt.Font("Ubuntu Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(243, 91, 105));
        jLabel10.setText("Sampai");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(57, 192, 186)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tg1Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tg1Hari, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tg1Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tg2Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tg2Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tg2Hari, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(tg1Hari, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(tg1Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(tg1Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(tg2Hari, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(tg2Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(tg2Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(txtDisplay)
                .addGap(149, 149, 149)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseClicked
        int hd1 = 0, bd1 = 0, td1 = 0;
        int hd2 = 0, bd2 = 0, td2 = 0;
        if (!(Integer.parseInt(tg1Hari.getText()) >= 31) && !(Integer.parseInt(tg1Hari.getText()) < 1) && !tg1Hari.getText().isEmpty()) {
            hd1 = Integer.parseInt(tg1Hari.getText());
        }
        if (!(Integer.parseInt(tg2Hari.getText()) >= 31) && !(Integer.parseInt(tg2Hari.getText()) < 1) && !tg2Hari.getText().isEmpty()) {
            hd2 = Integer.parseInt(tg2Hari.getText());
        }
        if (!(Integer.parseInt(tg1Bulan.getText()) >= 12) && !(Integer.parseInt(tg1Bulan.getText()) < 1) && !tg1Bulan.getText().isEmpty()) {
            bd1 = Integer.parseInt(tg1Bulan.getText());
        }
        if (!(Integer.parseInt(tg2Bulan.getText()) >= 12) && !(Integer.parseInt(tg2Bulan.getText()) < 1) && !tg2Bulan.getText().isEmpty()) {
            bd2 = Integer.parseInt(tg2Bulan.getText());
        }
        if (!(Integer.parseInt(tg1Tahun.getText()) < 1) && !tg1Tahun.getText().isEmpty()) {
            td1 = Integer.parseInt(tg1Tahun.getText());
        }
        if (!(Integer.parseInt(tg2Tahun.getText()) < 1) && !tg2Tahun.getText().isEmpty()) {
            td2 = Integer.parseInt(tg2Tahun.getText());
        }
        
        Date dt1 = new Date(hd1, bd1, td1);
        Date dt2 = new Date(hd2, bd2, td2);
        txtDisplay.setText(""+Date.selisihHari(dt1, dt2)+" hari");
    }//GEN-LAST:event_btnMouseClicked

    private void btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseEntered
        btn.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(243,91,105)));
        btnTxt.setForeground(new Color(243,91,105));
    }//GEN-LAST:event_btnMouseEntered

    private void btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMouseExited
        btn.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(57,192,186)));
        btnTxt.setForeground(new Color(57,192,186));
    }//GEN-LAST:event_btnMouseExited

    private void tg1HariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tg1HariKeyPressed
        
    }//GEN-LAST:event_tg1HariKeyPressed

    private void tg1HariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tg1HariKeyReleased
        
    }//GEN-LAST:event_tg1HariKeyReleased

    private void tg1HariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tg1HariKeyTyped
        if (tg1Hari.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_tg1HariKeyTyped

    private void tg1BulanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tg1BulanKeyTyped
        if (tg1Bulan.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_tg1BulanKeyTyped

    private void tg1TahunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tg1TahunKeyTyped
        if (tg1Hari.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_tg1TahunKeyTyped

    private void tg2HariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tg2HariKeyTyped
        if (tg2Hari.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_tg2HariKeyTyped

    private void tg2BulanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tg2BulanKeyTyped
        if (tg2Bulan.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_tg2BulanKeyTyped

    private void tg2TahunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tg2TahunKeyTyped
        
    }//GEN-LAST:event_tg2TahunKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn;
    private javax.swing.JLabel btnTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tg1Bulan;
    private javax.swing.JTextField tg1Hari;
    private javax.swing.JTextField tg1Tahun;
    private javax.swing.JTextField tg2Bulan;
    private javax.swing.JTextField tg2Hari;
    private javax.swing.JTextField tg2Tahun;
    private javax.swing.JLabel txtDisplay;
    // End of variables declaration//GEN-END:variables
}
